channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=23.2.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - ipython==8.12.2
  - numpy==1.22.2
  - torch==1.13.1
  - tqdm==4.62.3
name: mlflow-env
